require_one_sphere_one: false
allowed_balancing:
  value: [balanced, early_game_heavy, late_game_heavy]
  options: [balanced, early_game_heavy, late_game_heavy]
allowed_spreads:
  value: [clustered, wide_spread, mixed_spread]
  options: [clustered, wide_spread, mixed_spread]
allowed_patterns:
  value: [single_cluster, dual_cluster, early_late_split, middle_only]
  options: [single_cluster, dual_cluster, early_late_split, middle_only]
force_starter: false
allow_not_fully_evolved: false
max_evo_stage: 3
allowed_evo_methods:
  none: true
  level-up: true
  moon_stone: true
  fire_stone: true
  water_stone: true
  thunder_stone: true
  leaf_stone: true
  trade: false
  happiness: true
  trade_metal_coat: false
  trade_kings_rock: false
  trade_dragon_scale: false
  trade_upgrade: false
  level-up_atk_equal_def: true
  level-up_atk_greater_def: true
  level-up_def_greater_atk: true
  sun_stone: true
allow_legendaries: false
allow_duplicate_species: false
species_blacklist: []
bst_max: none
bst_min: none
allow_dual_type: true
type_distribution:
  value: anything_goes
  options: [anything_goes, no_overlap, all_share_one_type]
prescribed_type:
  value: none
  options: [none, normal, fire, water, grass, electric, flying, fighting, ice, psychic,
    ground, rock, poison, bug, dragon, ghost, steel, dark]
type_blacklist:
  value: []
  options: [normal, fire, water, grass, electric, flying, fighting, ice, psychic,
    ground, rock, poison, bug, dragon, ghost, steel, dark]
ensure_hm_coverage:
  FLASH: false
  CUT: true
  STRENGTH: true
  FLY: true
  SURF: true
  DIG: false
  TELEPORT: false
  SOFTBOILED: false
  WHIRLPOOL: true
  WATERFALL: true
  ROCK_SMASH: false
  HEADBUTT: false
allowed_acquisition_methods:
  starter: true
  walk: true
  surf: true
  old_rod: true
  good_rod: true
  super_rod: true
  poke_flute: true
  static_encounter: true
  trade: false
  gift: true
  purchase: true
  fossil_restore: true
  prize_window: true
  rock_smash: true
  bug_catching_contest: true
  squirt_bottle: true
  headbutt: true
  roaming: true
  rainbow_wing: true
  silver_wing: true
generation_filter:
  value: []
  options: [1, 2]
