require_one_sphere_one: false
allowed_balancing:
  value: [balanced, early_game_heavy, late_game_heavy]
  options: [balanced, early_game_heavy, late_game_heavy]
allowed_spreads:
  value: [clustered, wide_spread, mixed_spread]
  options: [clustered, wide_spread, mixed_spread]
allowed_patterns:
  value: [single_cluster, dual_cluster, early_late_split, middle_only]
  options: [single_cluster, dual_cluster, early_late_split, middle_only]
force_starter: false
allow_not_fully_evolved: false
max_evo_stage: 3
allowed_evo_methods:
  none: true
  level-up: true
  moon_stone: true
  fire_stone: true
  water_stone: true
  thunder_stone: true
  leaf_stone: true
  sun_stone: true
  trade: false
  trade_metal_coat: false
  trade_kings_rock: false
  trade_upgrade: false
  trade_deepseatooth: false
  trade_deepseascale: false
  happiness: true
  level-up_beauty: true
  level-up_empty_slot_extra_ball: true
  level-up_personality: true
  level-up_atk_greater_def: true
  level-up_def_greater_atk: true
  level-up_atk_equal_def: true
allow_legendaries: false
allow_duplicate_species: false
species_blacklist: []
bst_max: none
bst_min: none
allow_dual_type: true
type_distribution:
  value: anything_goes
  options: [anything_goes, no_overlap, all_share_one_type]
prescribed_type:
  value: none
  options: [none, normal, fire, water, grass, electric, flying, fighting, ice, psychic,
    ground, rock, poison, bug, dragon, ghost, steel, dark]
type_blacklist:
  value: []
  options: [normal, fire, water, grass, electric, flying, fighting, ice, psychic,
    ground, rock, poison, bug, dragon, ghost, steel, dark]
ensure_hm_coverage:
  CUT: true
  FLY: true
  SURF: true
  STRENGTH: true
  FLASH: false
  ROCK_SMASH: false
  WATERFALL: false
  DIVE: false
  DIG: false
  TELEPORT: false
  SOFTBOILED: false
allowed_acquisition_methods:
  starter: true
  walk: true
  surf: true
  old_rod: true
  good_rod: true
  super_rod: true
  static_encounter: true
  trade: false
  gift: true
  fossil_restore: true
  rock_smash: true
  dive: true
  roaming: true
  go_goggles: true
  devon_scope: true
  sealed_chamber_puzzle: true
  mirage_island: false
